/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.ui.MainFrame;

public class App {
    public static void main(String[] args) {
        new MainFrame();
    }
}
